name: mastodon_dart
description: A Dart library for accessing the Mastodon API.
version: 0.1.4
homepage: https://github.com/lukepighetti/mastodon_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  rxdart: ^0.23.1
  web_socket_channel: ^1.1.0

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
  test: ^1.14.2
